# -*- coding: utf-8 -*-
"""
flatten_tex.py -- turn a report that is split across dozens of \\input fragments into
one self-contained .tex file.

WHY
    cmdf_tree_models.step_latex writes only the skeleton of the report: the prose plus
    a line like \\input{tab_importance.tex} wherever a table belongs. Each table lives
    in its own file written by whichever Python function computed it. That is fine for
    regenerating numbers, but it means a sentence you can see in the PDF may not exist
    anywhere in the main .tex, so editing wording by hand means hunting through 23
    fragment files.

    This module inlines every fragment into one file. Figures stay as
    \\includegraphics references because those point at PNGs, not text.

MARKERS
    Each inlined block is wrapped in a comment naming the file it came from and the
    Python function that writes it, so a number that needs recomputing can still be
    traced back to its generator:

        % >>> BEGIN tab_importance.tex  (generated by cmdf_tree_models.step_importance)
        ...
        % <<< END tab_importance.tex

RUN
    python flatten_tex.py result_final_new_update15.tex
    python flatten_tex.py <in.tex> <out.tex>
"""
from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# which Python function writes which fragment, for the trace comments
SOURCE_OF = {
    "tab_comparison_expanded.tex": "cmdf_gbm_compare.report_table",
    "tab_comparison_esg.tex": "cmdf_gbm_compare.report_table",
    "tab_stability.tex": "cmdf_tree_models.step_stability",
    "tab_importance.tex": "cmdf_tree_models.step_importance",
    "tab_shap_all.tex": "cmdf_tree_models.step_shap",
    "tab_zones.tex": "cmdf_tree_models.step_zones",
    "tab_dm_test.tex": "cmdf_ensemble.dm_matrix",
    "tab_ranking_metrics.tex": "cmdf_ensemble.ranking_metrics",
    "tab_classify_compare.tex": "cmdf_tree_classify.main",
    "tab_featsel.tex": "cmdf_feature_select.evaluate_sets",
    "tab_featsel_delta.tex": "cmdf_feature_select.evaluate_sets",
    "tab_featsel_stability.tex": "cmdf_feature_select.evaluate_sets",
    "tab_featsel_dm.tex": "cmdf_feature_select.dm_brier",
    "tab_featsel_perm.tex": "cmdf_feature_select.permutation_importance_oos",
    "tab_featsel_cross.tex": "cmdf_feature_select.cross_model_randomisation",
    "tab_ai_data.tex": "cmdf_ai_pipeline_report.data_inventory",
    "tab_ai_defaults.tex": "cmdf_ai_pipeline_report.data_inventory",
    "tab_ai_discrimination.tex": "cmdf_ai_pipeline_report.collect_discrimination",
    "tab_ai_leadtime.tex": "cmdf_ai_pipeline_report.collect_leadtime",
    "tab_ai_alarmload.tex": "cmdf_ai_pipeline_report.collect_alarm_load",
    "tab_a2_compare.tex": "cmdf_approach2_compare.write_outputs",
    "tab_a2_leadtime.tex": "cmdf_approach2_compare.write_outputs",
    "tab_importance_default.tex": "make_importance_default.native_table",
    "tab_shapdef_all.tex": "make_importance_default.shap_table",
    "tab_imp_default_summary.tex": "make_importance_default (permutation summary)",
}

INPUT_RE = re.compile(r"^([ \t]*)\\input\{([^}]+)\}[ \t]*$", re.MULTILINE)


def resolve(name, base):
    """LaTeX lets \\input omit the .tex suffix."""
    for cand in (name, name + ".tex"):
        p = os.path.join(base, cand)
        if os.path.isfile(p):
            return p
    return None


def flatten(path, base=None, depth=0, seen=None, stats=None):
    base = base or os.path.dirname(os.path.abspath(path))
    seen = seen if seen is not None else set()
    stats = stats if stats is not None else {"inlined": 0, "missing": []}
    text = open(path, encoding="utf-8").read()

    def repl(m):
        indent, name = m.group(1), m.group(2).strip()
        target = resolve(name, base)
        if target is None:
            stats["missing"].append(name)
            return m.group(0)                      # leave it alone, do not lose it
        key = os.path.basename(target)
        if depth > 8 or target in seen:
            return m.group(0)
        seen.add(target)
        body = flatten(target, base, depth + 1, seen, stats).rstrip("\n")
        stats["inlined"] += 1
        src = SOURCE_OF.get(key)
        head = (f"{indent}% >>> BEGIN {key}"
                + (f"  (generated by {src})" if src else "")
                + f" -- edit the wording here, rerun the generator only to refresh "
                  f"the numbers")
        tail = f"{indent}% <<< END {key}"
        return "\n".join([head, body, tail])

    return INPUT_RE.sub(repl, text)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    src = args[0] if args else "result_final_new_update15.tex"
    if not os.path.isabs(src):
        src = os.path.join(HERE, src)
    dst = args[1] if len(args) > 1 else src
    if not os.path.isabs(dst):
        dst = os.path.join(HERE, dst)

    if not os.path.isfile(src):
        raise SystemExit(f"not found: {src}")

    stats = {"inlined": 0, "missing": []}
    out = flatten(src, stats=stats)

    if os.path.abspath(src) == os.path.abspath(dst):
        bak = dst + ".split.bak"
        if not os.path.exists(bak):
            with open(bak, "w", encoding="utf-8") as f:
                f.write(open(src, encoding="utf-8").read())
            print(f"kept the fragment version as {os.path.basename(bak)}")

    with open(dst, "w", encoding="utf-8") as f:
        f.write(out)

    left = len(INPUT_RE.findall(out))
    print(f"inlined {stats['inlined']} fragments into {os.path.basename(dst)}")
    print(f"lines: {len(out.splitlines()):,}   size: {len(out.encode('utf-8')):,} bytes")
    print(f"\\input lines remaining: {left}")
    if stats["missing"]:
        print("could not resolve (left as-is):", ", ".join(stats["missing"]))
    print("\nfigures stay as \\includegraphics references; they point at PNG files")


if __name__ == "__main__":
    main()
